apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name 必须匹配下面的spec字段：<plural>.<group>
  name: network.samplecrd.k8s.io
spec:
  # group 名用于 REST API 中的定义：/apis/<group>/<version>
  group: samplecrd.k8s.io
  # version 名用于 REST API 中的定义：/apis/<group>/<version>
  versions:
    - name: v1 # 版本名称，比如 v1、v2beta1 等等
      served: true
      storage: true # 是否开启通过 REST APIs 访问 `/apis/<group>/<version>/...`
  names:
    kind: Network
    plural: networks
  scope: Namespaced


